Fixet path to the skript
Harast/New pull request #4
Opened 2020-03-29 23:33 UTC by Harast

That`s all?

2020-03-30 07:34 UTC, DrBAXA requested changes
Unfortunately, you still need to use spaces instead of tabs. Not sure how it looks for you in your editor, but here it's not properly formated. Take a look at the code in a browser. Most of the code is indented too far.

Your editor probably has a setting to replace a tab with 4 spaces.

2020-03-30 14:57 UTC, Harast reviewed
Like this?

2020-03-30 16:02 UTC, DrBAXA commented
Something is still wrong. Function Fizz_Buzz still looks wrong. Also, you have partially replaced tabs with spaces. There should not be tabs at all

2020-04-02 18:10 UTC, DrBAXA approved these changes

2020-04-02 18:10 UTC, merged